version: "3"
services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  app:
    image: abhijitkatore/carparkingapi_app
    container_name: CarParking
    ports:
      - 8080:8080

volumes:
  mongo_db: {}
