swagger: "2.0"
info:
  title: CarParking API
  description: Demo API application for CarParking
  version: 1.0.0
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /user:
    get:
      summary: Returns a list of users.
      description: Returns a list of users.
      responses:
        "200":
          description: A JSON array of user
    post:
      summary: Adds a new user
      parameters:
        - in: body
          name: body
          description: Adds a new user

          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
              age:
                type: integer
            example:
              fname: "A"
              lname: "K"
              age: 21

      responses:
        "200":
          description: OK
  /slot:
    get:
      summary: Returns a list of Available slots.
      description: Returns a list of Available slots.
      responses:
        "200":
          description: A JSON array of Slot
